language: cpp

matrix:
        include:
                - os: linux
                  name: "Linux Build"
                  before_script:
                          - sudo apt-get install -y xorg-dev
                  script:
                          - mkdir build
                          - cd build
                          - cmake ..
                          - make
                - os: windows
                  name: "Windows Build"
                  script:
                          - mkdir build
                          - cd build
                          - cmake ..
                          - cmake --build . --config Release 2>&1 >build.log
